name: API CI
on:
    push:
        paths:
            - 'apps/api/**'
            - 'database/**'
            - 'shared/**'
    pull_request:
        paths:
            - 'apps/api/**'
            - 'database/**'
            - 'shared/**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Build CPP API
              run: |
                cd apps/api
                cmake -B build
                cmake --build build
            - name: Run tests
              run: |
                    cd apps/api/build
                    ./test